name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create public directory
        run: mkdir -p public

      - name: Create index.html with AWS config
        run: |
          echo "<!DOCTYPE html>" > public/index.html
          echo "<html lang='en'>" >> public/index.html
          echo "<head>" >> public/index.html
          echo "    <meta charset='UTF-8'>" >> public/index.html
          echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>" >> public/index.html
          echo "    <title>Team Table Assigner</title>" >> public/index.html
          echo "    <link rel='stylesheet' href='styles.css'>" >> public/index.html
          echo "    <link href='https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap' rel='stylesheet'>" >> public/index.html
          echo "    <script src='https://sdk.amazonaws.com/js/aws-sdk-2.799.0.min.js'></script>" >> public/index.html
          echo "    <script>" >> public/index.html
          echo "    window.AWS_ACCESS_KEY_ID = '${{ secrets.AWS_ACCESS_KEY_ID }}';" >> public/index.html
          echo "    window.AWS_SECRET_ACCESS_KEY = '${{ secrets.AWS_SECRET_ACCESS_KEY }}';" >> public/index.html
          echo "    </script>" >> public/index.html
          echo "</head>" >> public/index.html
          echo "<body>" >> public/index.html
          echo "    <button class='top-right' onclick='toggleDarkMode()'>Toggle Dark Mode</button>" >> public/index.html
          echo "    <div class='main-content'>" >> public/index.html
          echo "        <div class='controls'>" >> public/index.html
          echo "            <h1>Team Table Assigner</h1>" >> public/index.html
          echo "            <input type='date' id='datePicker' class='dropdown'>" >> public/index.html
          echo "            <div class='row'>" >> public/index.html
          echo "                <select id='teamSelectA' class='dropdown'>" >> public/index.html
          echo "                    <option value='Advertising'>Advertising</option>" >> public/index.html
          echo "                    <option value='Ad Technology'>Ad Technology</option>" >> public/index.html
          echo "                    <option value='BI'>BI</option>" >> public/index.html
          echo "                    <option value='OTT'>OTT</option>" >> public/index.html
          echo "                </select>" >> public/index.html
          echo "                <select id='teamSelectB' class='dropdown'>" >> public/index.html
          echo "                    <option value='Advertising'>Advertising</option>" >> public/index.html
          echo "                    <option value='Ad Technology'>Ad Technology</option>" >> public/index.html
          echo "                    <option value='BI'>BI</option>" >> public/index.html
          echo "                    <option value='OTT'>OTT</option>" >> public/index.html
          echo "                </select>" >> public/index.html
          echo "            </div>" >> public/index.html
          echo "            <div class='row'>" >> public/index.html
          echo "                <div id='teamA' class='team'></div>" >> public/index.html
          echo "                <div id='teamB' class='team'></div>" >> public/index.html
          echo "            </div>" >> public/index.html
          echo "            <button onclick='assignTeams()'>Assign Teams</button>" >> public/index.html
          echo "        </div>" >> public/index.html
          echo "        <div class='results' id='results'>" >> public/index.html
          echo "            <h2>Results</h2>" >> public/index.html
          echo "            <ul id='resultsList'></ul>" >> public/index.html
          echo "        </div>" >> public/index.html
          echo "    </div>" >> public/index.html
          echo "    <div id='myModal' class='modal'>" >> public/index.html
          echo "        <div class='modal-content'>" >> public/index.html
          echo "            <div class='loader'></div>" >> public/index.html
          echo "            <p>Assigning teams, please wait...</p>" >> public/index.html
          echo "        </div>" >> public/index.html
          echo "    </div>" >> public/index.html
          echo "    <script src='script.js'></script>" >> public/index.html
          echo "</body>" >> public/index.html
          echo "</html>" >> public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./public
